image: openjdk:8-jdk-stretch

pipelines:
  tags:
    '*':
      - step:
          caches:
            - gradle
          script:
            - ./gradlew assemble
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"`find build/libs -name '*.war'`"
