definitions:
  steps:
  - step: &build-war
      image: openjdk:8
      caches:
        - gradle
      script:
        - umask 0022
        - ./gradlew assemble
      artifacts:
        - build/libs/*.war

pipelines:
  default:
    - step: *build-war
  tags:
    '*':
      - step: *build-war
      - step:
          image: openjdk:8
          caches:
            - gradle
          script:
            - USERNAME=$GH_PR_USER TOKEN=$GH_PR_TOKEN ./gradlew publish
