aggregratedFeed:
  type: rss_2.0
  title: Personalized Feed
  description: Personalized feed to use in MyCPP
  author: Various Authors
  link: https://my.cpp.edu

# The oldest an article can be, in weeks
maxAge: 4

feeds:
  general:
  - https://polycentric.cpp.edu/tag/student-and-campus-life/feed/
  - https://polycentric.cpp.edu/tag/student-success/feed/
  - https://polycentric.cpp.edu/tag/college-rankings/feed/
  - https://polycentric.cpp.edu/tag/campus-construction/feed/
  - https://polycentric.cpp.edu/tag/tuition/feed/
  - https://polycentric.cpp.edu/tag/safety-alert/feed/
  - https://polycentric.cpp.edu/tag/university-news/feed/
  - https://polycentric.cpp.edu/tag/students/feed/
  - https://polycentric.cpp.edu/tag/campus-safety/feed/
  - https://polycentric.cpp.edu/tag/university-police/feed/
  - https://polycentric.cpp.edu/tag/bronco-advising-center/feed/
  - https://polycentric.cpp.edu/tag/asi/feed/
  - https://polycentric.cpp.edu/tag/associated-students-inc/feed/
